# spring
spring:
  # profiles
  profiles:
    active: local
# framework
framework:
  # swagger
  swagger:
    base-package: com.looksee.audit-service.web.controller
# log
logging:
  config: classpath:config/logback-spring.xml
  level:
    root: warn
    com.looksee.audit-service: info
# mybatis plus
mybatis-plus:
  type-aliases-package: com.looksee.audit-service.entity,com.looksee.audit-service.model.*
  mapper-locations: classpath:mappers/*Mapper.xml
#Resilience4j
resilience4j.retry:
    configs:
        default:
            maxAttempts: 5
            waitDuration: 5s
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.util.concurrent.TimeoutException
                - java.io.IOException
                - java.net.SocketException
                - java.net.ConnectException
                - java.lang.Exception
        neoforj:
            maxAttempts: 10
            waitDuration: 10s
            retryExceptions:
                - org.neo4j.ogm.exception.ConnectionException
                - org.neo4j.driver.exceptions.SessionExpiredException
                - org.neo4j.driver.exceptions.DiscoveryException
                - org.neo4j.driver.exceptions.TransientException
                - org.neo4j.ogm.exception.TransactionException
                - org.neo4j.ogm.exception.CypherException
                - java.net.SocketException
                - java.util.NoSuchElementException
    instances:
        neoforj:
            baseConfig: neoforj
        default:
            baseConfig: default